version: '3'
services:
  # caching service
  # backend rest api
  web:
    build: .
    container_name: sodiumdev-web
    environment:
      - NODE_ENV=production
      - SECRET=Rtefh4ZjQOtsLe47lc6ds6OUu2O5w4w0jxa0XYMM
      - MONGODB_URI=mongodb://mongodb:27017/sodiumdev
      - REDIS_HOST=redis
      - REDIS_PORT-6379
    depends_on:
      - mongodb
    ports:
      - '5000:5000'

  mongodb:
    image: mongo:4.4.3
    hostname: mongodb
    container_name: sodiumdev-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/dbconfig

  redis:
    image: redis:latest
    hostname: redis
    container_name: sodiumdev-redis
    ports:
      - 6379:6379

volumes:
  mongodb:
  mongodb_config:
